# Generated by Django 4.2.5 on 2023-09-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(verbose_name='Article number')),
                ('title_in_transliteration', models.CharField(max_length=255, verbose_name='Title in transliteration')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('summary', models.CharField(max_length=250, verbose_name='Summary')),
                ('number_of_views', models.IntegerField(verbose_name='Number of views')),
                ('favorites', models.BooleanField(default=False, verbose_name='Favorites')),
                ('assessment', models.CharField(choices=[('-1', '0')], default=0, max_length=255, verbose_name='Assessment')),
                ('rating', models.IntegerField(verbose_name='Rating')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
