# Generated by Django 4.2.5 on 2023-09-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='assessment',
            field=models.CharField(choices=[('-1', 'Negative'), ('0', 'Neutral'), ('1', 'Positive')], default=0, max_length=255, verbose_name='Assessment'),
        ),
    ]
