# Generated by Django 4.2.5 on 2023-09-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_alter_article_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.PositiveIntegerField(verbose_name='Article number'),
        ),
        migrations.AlterField(
            model_name='article',
            name='number_of_views',
            field=models.PositiveIntegerField(verbose_name='Number of views'),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.PositiveIntegerField(verbose_name='Rating'),
        ),
    ]
