# Generated by Django 4.2.5 on 2023-09-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_alter_article_article_alter_article_number_of_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Article number'),
        ),
    ]
