# Generated by Django 4.2.5 on 2023-09-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0004_remove_article_id_alter_article_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='number_of_views',
            new_name='views',
        ),
    ]
