# Generated by Django 4.2.5 on 2023-09-22 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_rename_number_of_views_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 5, 30, 1, 453213, tzinfo=datetime.timezone.utc), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of views'),
        ),
    ]
