# Generated by Django 4.2.5 on 2023-09-22 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0007_alter_article_author_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 6, 26, 21, 432208, tzinfo=datetime.timezone.utc), verbose_name='Creation date'),
        ),
    ]
