# Generated by Django 4.2.5 on 2023-09-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0011_alter_article_title_in_transliteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_in_transliteration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title in transliteration'),
        ),
    ]
