# Generated by Django 4.2.5 on 2023-09-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0012_alter_article_title_in_transliteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='Article text'),
        ),
    ]
