# Generated by Django 4.2.5 on 2023-09-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0014_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Article number'),
        ),
    ]
