# Generated by Django 4.2.5 on 2023-09-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0015_alter_article_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Article number'),
        ),
    ]
